### ISSUE TITLE
SASS Nested Properties

### ISSUE THREAD

**Issue by tommyschaefer** [thoughtbot/guides#301]
This question refers to the SASS style guide.

What are the feelings on using SASS nested properties? I have something like:

```
text-align: ...;
text-decoration: ...;
text-transform: ...;
```

And I'm wondering if its better to use the following in this case:

```
text: {
  align: ...;
  decoration: ...;
  transform: ...;
}
```

And whether you would do the same for two declarations as well?

```
font-size: ...;
font-weight: ...;
```

to

```
font: {
  size: ...;
  weight: ...;
}
```

**Comment by jferris** [comment]
@thoughtbot/design any thoughts?

**Comment by conchan** [comment]
For things like `font` and `background`, I usually use declare them with shorthand properties. However, there are times when I'm setting something like `border` for different sides and have considered nesting. Still, I don't actually do it. Since we keep our styles in alphabetical order, usually those properties would be grouped together anyway, and so I don't personally see the benefits of breaking them down further with SASS-nesting.

**Comment by joshuaogle** [comment]
I agree with @conchan. I like that the nested styles are there, but very rarely does it actually feel DRYer if you only have two or three styles to nest. I wouldn't want to *discourage* nesting, but it seems like most people don't.

**Comment by tommyschaefer** [comment]
Okay, that sounds good! Thank you all for the feedback! :smile:
