### ISSUE TITLE
What is the purpose of the guides

### ISSUE THREAD

**Issue by mjankowski** [thoughtbot/guides#312]
Some of the discussions in Guides PRs lately leads me to believe that a PR to the README of the guides repo clarifying what the entire purpose of the guides is, might be beneficial in steering these conversations towards being more focused and productive.

There's very little in the way of high level guidance around how to think about these things, and I suspect that encountering all of this as a new employee or random internet stranger could be confusing right now.

Are these rules to always enforce on every project?

Are these a starting point which we expect many projects to override?

Are these just a snapshot in time and we expect some churn in here as preferences evolve?

Are these  supposed to be limited only to things we ALL agree on?  That just a consensus agree on?

**Comment by gabebw** [comment]
I've thought of them as "rules to enforce on every project", and I do "expect some churn as preferences evolve" (cf. single vs double quotes).

If we're not enforcing something on every project, then I think we should drop that guideline (and let people decide on a per-project basis). I do note that we have a lot more things that are being decided on a per-project basis instead of being enforced in the guides now, vs say 2 years ago. That's probably because we have more people and more offices.

I think having a core of "ALWAYS DO THESE THINGS" is valuable. Beyond that, maybe we should drop the stuff that's not valuable on every project?

**Comment by drapergeek** [comment]
> I think having a core of "ALWAYS DO THESE THINGS" is valuable. Beyond that, maybe we should drop the stuff that's not valuable on every project?

I see the guides as suggestions for the most part. I don't ever take them as written in stone. They are an easy way to settle a discussion but we're all professional enough to know when we should break rules and I think we regularly break them.

I also believe that the guides help to preserve our "culture" across  the company. We're in many cities and offices now. We're hiring a lot of new people. Some things that aren't absolutely required are still great to let people know that is how we normally work and to spread that information.

I think following the "Sandi Metz rule breaking guidelines" is probably the best way to determine if you shouldn't follow it: convince your team members, otherwise stick to the rules.

**Comment by mike-burns** [comment]
I see the style section of the guides as a useful way to avoid ever having a debate over whether to choose `reduce` vs `inject`, single quotes versus double quotes, etc. If those things ever get changed after the first time, the style guide has failed.

The best practices section ... the audience of that is not quite clear to me.

**Comment by gylaz** [comment]
> If those things ever get changed after the first time, the style guide has failed.

Say we picked `inject` because that's what was popular at the time. With time, a bunch of new languages came out and all of them used `reduce`. All the cool kids are saying `reduce` now, and when someone uses `inject` the cool kids respond with a blank stare.

I think that's a good time to re-evaluate the particular style guide rule. I can't agree that style guide fails if we change a style rule because the industry/community evolved.

**Comment by jferris** [comment]
> Are these rules to always enforce on every project?

I think these are guidelines which we should consider on every project. For some guidelines, they're so universal that it's hard to imagine a situation where you'd violate them ("Don't test private methods"). For others, it states a default preference which we should adhere t until there's a good reason to deviate ("Avoid optional parameters").

> Are these a starting point which we expect many projects to override?

I don't believe we should have per-project guides in general. It creates friction when switching projects, and it makes it harder to configure editors and other tools to correctly format and lint code.

> Are these just a snapshot in time and we expect some churn in here as preferences evolve?

I'm not sure I understand this question. We expect everything to evolve, always, forever. So yes, they're just a snapshot in time, just like everything else we preach, create, and use.

> Are these supposed to be limited only to things we ALL agree on? That just a consensus agree on?

I don't think a unanimous vote on almost anything is realistic. I think a strong majority is sufficient.

**Comment by jferris** [comment]
> If those things ever get changed after the first time, the style guide has failed.

I don't understand why that's a failure. It still reduces the number of arguments we need to have about style, and the end result should be a consistent style throughout the code base. Using a tool like Hound, we can continually move a code base, no matter how new or old, towards a style guide which we all created as a team. This seems better than using a style we're no longer satisfied with on every future project.

I think it's natural for styles to evolve. For one, there's an aesthetic element which will change for any number of reasons. For another, as we get exposed to more code, our thoughts on what looks good or reads well will change, because we get used to ideas from other communities.

As an example, some of us were tickled by Ruby's rhyming collection methods (collect, detect, reject, select) early on. After working in other languages, we found it was easier to keep a smaller mental map if we used more widely-known names like "map." I had fun whistling "Alice's Restaurant" while typing out `collect` calls for years, but I'm happy we're using `map` now.

> The best practices section ... the audience of that is not quite clear to me.

The primary audience is ourselves. The secondary audience is anybody who's interested.

Some of the best practices may seem obvious, but that's only because we've already agreed on them. Things like "exceptions should be exceptional" are not universally known. When a new team member reads through Best Practices, new ideas or things they disagree with give them a chance to ask questions and understand how the team thinks.

This repository is also a useful collection of discussions. We use pull requests to change the guide. This means that every best practice introduced is also a discussion we get to have as a team, as well as a historical record of that discussion. The discussion behind each guideline is discoverable through Git and GitHub. I think that's really powerful, and just asking questions in real-time chat or tools like Basecamp doesn't compare.

As a side-effect, listing out some of our development practices gives outside parties an opportunity to see how thoughtbot thinks and what we care about.

**Comment by mike-burns** [comment]
One of our best practices is "Avoid global variables". If we are really the primary audience of that one, then I'm disappointed.

I'm also of the opinion that a best practice does not change; otherwise it's just a practice. "Use only one instance variable in each view" strikes me as a fad that will change, and not a best practice; "Use SendGrid or Amazon SES to deliver email ..." even moreso.

Things like "Use quotes around every $variable and $(...) expression ..." or "Prefer checking exit statuses over output in if statments ..." are descriptions of shell prorgamming. They are indeed best practice, in that it's how shell programming works and it's not going to change, but it's also not something that belongs in a best practices guide.

Maybe best practices would be best replaced with something that covers: these are the non-industry-standard things that we do. Some examples might be "Don't support IE6 or IE7" or "Don't write code that guesses at future functionality."

**Comment by jferris** [comment]
> One of our best practices is "Avoid global variables". If we are really the primary audience of that one, then I'm disappointed.

Sometimes I feel like it's just positive to get down some of the ones we all agree on. Then it feels less daunting when we have to argue about more controversial practices.

> I'm also of the opinion that a best practice does not change; otherwise it's just a practice.

I think everything is going to change. We're recording what we've found to be the best practices so far. Later, we'll find out some of these were bad ideas or we'll find newer ideas that are even better. I don't understand the desire for best practices or styles that never change.

> They are indeed best practice, in that it's how shell programming works and it's not going to change, but it's also not something that belongs in a best practices guide.

Why doesn't it belong in a best practices guide?

Personally, I still find shell to be tricky, and I've referred to this list a number of times when writing shell code. I've also referred to the pull request where we added these guidelines, which helped me understand how to write better shell.

> Maybe best practices would be best replaced with something that covers...

Are you suggesting a rename? I'm cool with that if you can come up with a better name.

Are you suggesting a split or general reorganization? I'm also down for that.

Are you suggesting deleting most of the best practices? I don't think I'd like to do that, but I'm open to being convinced if you'd like to remove some of them.

**Comment by jferris** [comment]
I think this was a good discussion, but there don't seem to be any immediate action items here. I'm going to close this; feel free to continue commenting if you have further thoughts.

**Comment by mjankowski** [comment]
My initial issue description here said:

> a PR to the README of the guides repo clarifying what the entire purpose of the guides is, might be beneficial in steering these conversations towards being more focused and productive

I still think that would help, but I still can't do it myself, because I don't know the answer.

**Comment by mike-burns** [comment]
@mjankowski you could take advantage of the fact that programmers hate when people are wrong: make a PR with an updated README stating what the entire purpose of the guide is, and then wait for someone to correct you.

**Comment by mjankowski** [comment]
Opened a PR, hoping someone will correct me. https://github.com/thoughtbot/guides/pull/325
