### ISSUE TITLE
How to setup common variables for Rspec without its, let, let!, specify or before?

### ISSUE THREAD

**Issue by rafaelcgo** [thoughtbot/guides#322]
"Avoid its, let, let!, specify, and before in RSpec."

How to "setup" common variables for RSpec tests then?

**Comment by teoljungberg** [comment]
We inline them in each test-case, sure that's cause for repetition. But it also makes all of the tests self-contained and easier to move around/delete without having leftovers

**Comment by teoljungberg** [comment]
Hopefully that answers your question about how we structure our tests

**Comment by rafaelcgo** [comment]
Ok, thanks for the clarification. :+1:

**Comment by mcmire** [comment]
To expound a little bit...

Oftentimes `let`s are used to build objects. We find that objects aren't always built the same way in each test -- maybe they need to be customized for certain cases. Some people will define another `let` if they need to customize a component of that object, and then override the `let` later if need be:

``` ruby
describe SomeClass do
  let(:birthday) { Date.today }
  let(:customer) { create(:customer, birthday: birthday) }
  let(:order) { create(:order, customer: customer) }

  context "if the order's customer has a birthday" do
    it "returns the date" do
      ...
    end
  end

  context "if the order's customer does not have a birthday" do
    let(:birthday) { nil }

    it "returns nil" do
      ...
    end
  end
end
```

We find that overriding methods like this leads to confusion when reading the test in isolation, particularly if you have a bunch of objects that depend on each other.

Instead of shoving all the setup for a test in a bunch of `let`s, we find it more helpful to list each step explicitly in that test, using builder methods to build the objects we need instead. These methods will accept options so we can customize what gets built:

``` ruby
describe SomeClass do
  context "if the order's customer has a birthday" do
    it "returns the date" do
      order = create_order(customer_birthday: Date.today)
      ...
    end
  end

  context "if the order's customer does not have a birthday" do
    it "returns nil" do
      order = create_order(customer_birthday: nil)
      ...
    end
  end

  def create_order(options = {})
    customer = create(:customer, birthday: options[:customer_birthday])
    create(:order, customer: customer)
  end
end

**Comment by rafaelcgo** [comment]
NOW I get it! @mcmire Thanks for the attention!

**Comment by dideler** [comment]
Very useful explanation, thanks!
