### ISSUE TITLE
Multiple factory files

### ISSUE THREAD

**Issue by rupurt** [thoughtbot/guides#352]
Howdy Thoughtbotters, 

I was wondering what some of the reasons are behind using a [single `factories.rb` file](https://github.com/thoughtbot/guides/tree/master/style/testing#factories)?

I feel like this gets unwieldy past ~10 factories. Below are some of the reasons I propose using multiple files:

- Maintaining the order in a single file is a manual process
- Github PR's sometimes obscure the necessary context around a diff which makes it difficult to catch alphabetical ordering errors
- Multiple files gives us automatic ordering in a directory
- Adding a new parent factory is as simple as adding a new file

cc/ @parisyee @attack @ryanong

**Comment by JuanitoFatas** [comment]
Here is a live example: https://github.com/thoughtbot/hound/blob/master/spec/factories.rb for single factories.rb

**Comment by mcmire** [comment]
Honestly, I'm not sure if there's a great answer for this -- I think the simple answer is "tradition".

*Personally*, I feel like splitting up factories into multiple files makes things more complicated than they need to be when a project is first starting. As the project grows, I can totally see a need to split up the factories down the road, especially as more traits are added to existing factories. So for me it's an attempt to keep things simple and accessible at first.

@joshuaclayton When you run `rails g factory_girl:install`, does this generate a file by default, or a folder?

**Comment by drapergeek** [comment]
I have a few reasons:
* It allows us to keep similar concepts together and prevent duplication in the factories. A good example is an auto-incrementing email address. I've seen this defined multiple times in projects with split files.
* It encourages the factories to stay small. I've seen a lot of projects that seem like they need multiple files for factories but it was because the factories were being used in excessive ways by defining a lot more attributes than was necessary.
* When a project is small, it's easier to scan for what is available for us in the tests.

Eventually, projects may get to a point where the factories file grows out of hand and needs to be split up. In that case, I think it's up to the team to decide how the file should be split. One model per file may not be the best decision, they may find that splitting by concept or area of the application makes more sense. I think by starting with a single file we've left the door open to decide what the best way to organize the files in the future is, if that becomes necessary.

**Comment by mcmire** [comment]
> It encourages the factories to stay small. I've seen a lot of projects that seem like they need multiple files for factories but it was because the factories were being used in excessive ways by defining a lot more attributes than was necessary.

Yup, that's well said. I have seen that too.

**Comment by rupurt** [comment]
@mcmire agreed that there's no silver bullet :smile: I'm hoping to open up conversation to include more of the `why?` in the styleguide rules.

@drapergeek I like the idea of grouping concepts together rather than 1 file=1 factory

To avoid duplicate sequences how do feel feel about defining them in a separate file e.g. 

```ruby
# spec/factories/sequences.rb
FactoryGirl.define do
  sequence(:email) { |n| "foo-#{n}@bar.com" }
end
```

**Comment by drapergeek** [comment]
>To avoid duplicate sequences how do feel feel about defining them in a separate file e.g.

I think the silver bullet statement applies here as well. That could work out OK but it's not just sequences, I've seen this happen to shared traits as well.

A lot of these ideas are also dependent on the codebase and team. If your team knows to go looking in a sequence file before defining something, great, but that's not a normal convention so when onboarding new team members you may run into issues.

I think the key really does come down to keeping the factories small, regardless of the way they're organized.

**Comment by mjankowski** [comment]
Closing because no updates in ~5 months and no real consensus.  Please re-open if someone wants to move this forward in a way that leads to a PR.
