### ISSUE TITLE
Update how-to guide on feature-testing a Rails app’s Javascript?

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/guides#585]
We have a [guide on how to feature-test a Rails app’s JavaScript](https://github.com/thoughtbot/guides/tree/master/how-to#-feature-test-a-rails-apps-javascript) that suggests using capybara-webkit. We also have a [blog post on how to swap capybara-webkit for Chromedriver](https://thoughtbot.com/blog/headless-feature-specs-with-chrome) and Suspenders (our Rails template) uses Chromedriver (see https://github.com/thoughtbot/suspenders/commit/cf78134766c689dab1d9e5db2f3be454ba81f487).

Should we update this guide? Should it be removed if it’s no longer providing value? Something else?

**Comment by composerinteralia** [comment]
I think suspenders should be the source of truth for how to set up specs

If we keep the spec as an example, we should convert it into a [system spec](https://relishapp.com/rspec/rspec-rails/v/3-9/docs/system-specs/system-spec) instead of a feature spec. I would also want us to give some indication of where `create` and  `sign_in_as` are coming from.

I am in favor of either removing this section or replacing it with a few links (to suspenders, to the rspec-rails docs, etc.)

**Comment by tysongach** [comment]
Maybe we remove this ‘how-to’ and add some details to our [‘Best Practices’](https://github.com/thoughtbot/guides/tree/master/best-practices) under the Rails and/or Testing heading(s) about using system tests?
