### ISSUE TITLE
Replace Ruby style guide with standard

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/guides#605]
As we move toward using [standard](https://github.com/testdouble/standard), we can probably replace most or all of our [Ruby style guide](https://github.com/thoughtbot/guides/tree/master/style/ruby) with "• Use standard"

**Comment by georgebrock** [comment]
I'm in favour of this kind of change. I've always been a fan of our [Python style guide][1]'s brevity.

Should this be a PR? We could then more easily discuss the specifics, e.g. comment on individual bullet points that we should keep because they aren't covered by an auto-formatter.

[1]: https://github.com/thoughtbot/guides/tree/master/style/python
