### ISSUE TITLE
Change master to main in thoughtbot/guides

### ISSUE THREAD

**Issue by louis-antonopoulos** [thoughtbot/guides#627]
Related to [handbook PR 1811](https://github.com/thoughtbot/handbook/pull/1811)

I started making a suggestion on [a handbook PR](https://github.com/thoughtbot/handbook/pull/1828) to use `main` instead of `master` in a link (https://github.com/thoughtbot/guides/tree/master/code-review), but when I tested it to make sure it worked, it failed because `thoughtbot/guides` hasn't been migrated yet.

If new handbook PRs have to refer to `master` for some links, it will start to undo the work in [PR 1811](https://github.com/thoughtbot/handbook/pull/1811) and we'll have to do another pass on the handbook repo.

**Comment by mike-burns** [comment]
This is what I know about renaming the default branch on existing projects: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

And here's the Trello card for tracking things: https://trello.com/c/1cxPEAlZ/752-use-main-as-the-default-git-branch

**Comment by KurodaSteph** [comment]
@louis-antonopoulos If I'm reading this correctly, Github is asking people to wait until the EOY, then we could change `thoughtbot/guides` root to `main` and anything connected to that will automatically change - is that how that works?

If so, I suppose we could wait. If not, I'd like to help the company fully switch to `main`. As a person who doesn't typically deep-dive into Github, I'd offer to pair with someone before EOY and manually make changes if it's under, say, 100 references (I suspect I might be underestimating the number of manual changes needed), and simple enough (although tedious). Would that help?

>By the end of the year, we'll make it seamless for existing repositories to rename their default branch. When you rename the branch, we’ll retarget your open PRs and draft releases, move your branch protection policies, and more - all automatically. And, we’re also looking into redirecting users who git fetch or git clone the old branch name to the new branch name (with a warning and instructions to update their local clone), so it’s easy for your contributors to move.

cc @samkap re: https://github.com/thoughtbot/handbook/issues/1771

**Comment by jferris** [comment]
The references to public repositories are hard to find and can't necessarily be updated: they're public, and anybody can link to them, so all the various blogs, Tweets, and GitHub comments out there will have the old URL, which includes "master."

However, GitHub will now [redirect URLs referencing a deleted master branch], so changing the default branch here will mean those URLs continue to work. Since the guides are primarily a source of documentation (URLs) and not automation, I think it would be both safe and meaningful to proactively rename the default branch for this repository now rather than waiting for GitHub.

I'm going to update the default branch for this repository.

[redirect URLs referencing a deleted master branch]: https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/

**Comment by jferris** [comment]
I have:

* Changed the default branch to `main`
* Updated open pull requests to reference `main` instead of `master`
* Deleted the `master` branch
* Verified some URLs to see that `master` was redirected to main
